apiVersion: v1

kind: Service

metadata:
  name: backend-service
  labels:
    app: backend-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: backend-pod
